### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by KacperKlys** [mathew-fleisch/bashbot-example#1]
Hi @mathew-fleisch,

I would like to use your bashbot and I have some questions.
First thing, on the Slack website there is no such option as `Legacy Bot User`. You have to set all the permissions manually. Any ideas what type of the permission the bot should have?
Could you give me some more explanation about config.json file and `userIds`, `privateChannelId`, `logChannelId` parameters?
`userIds` corresponds to `App ID`? What is `logChannelId` and where I can find it?

**Comment by mathew-fleisch** [comment]
Hey there @KacperKlys 
Cool! I hope I can clear some things up for you. First, check out the blog post I recently wrote about Bashbot here https://github.com/mathew-fleisch/blog/blob/main/blog/2021-08-11/bashbot.md

The `legacy bot user` is an option when setting up a "classic app" there are screenshots on the main read-me of this repo to guide you through that process. Essentially, start by logging into slack in a browser, and visiting this url: https://api.slack.com/apps?new_classic_app=1 Bashbot does not require any additional permissions or "scopes" as slack calls them, except for it to be initially set up as a classic app with a legacy bot user attached.

As for the config.json I created an [examples](https://github.com/mathew-fleisch/bashbot/tree/main/examples) directory in the main Bashbot repo that describes various commands that can be set up. The fields you mentioned (`userIds`, `privateChannelId` and `logChannelId`) are not necessary to have values on the first start up of bashbot as they are used to administrate bashbot. Once you have Bashbot running, you can run `bashbot info` (https://github.com/mathew-fleisch/bashbot/tree/main/examples/info) to get your slack user id and the channel id where it was executed. Use those ids to restrict sensitive commands to specific channels, and/or set up a "log" channel that can be used for auditing purposes.

Let me know if you have any other questions!
Good Luck!

**Comment by KacperKlys** [comment]
@mathew-fleisch thanks for the explanation. Your blog was really useful.
Finally, I manged to find `legacy bot user` option. My problem was described here https://github.com/slackapi/hubot-slack/issues/584#issuecomment-750492637 - I didn't know that it makes a difference how you create an app in Slack.

I have a last question. Is there any way to get a user input from slack and pass it to the command? 
Like:
```
    {
      "name": "Open file",
      "description": |Open file",
      "help": "info",
      "trigger": "open <here_goes_my_argument>",
      "location": "./",
      "command": ["open <my_argument>"],
      "parameters": [],
      "log": false,
      "ephemeral": false,
      "response": "code",
      "permissions": ["all"]
    }

```
Thanks for your help

**Comment by mathew-fleisch** [comment]
Hey @KacperKlys 
I'm glad you got passed the first hurdle

As for user input, each Bashbot command includes a 'parameters' key/value pair where the value expects an array of objects. Each object in that array defines a possible parameter either by explicitly hard-coding a list of possible values or by generating valid values on the fly. For example, hard coding parameters would look like this:
```json
{
  "name": "Open file",
  "description": "Open file",
  "help": "bashbot open [my_file]",
  "trigger": "open",
  "location": "./",
  "command": ["open ${my_file}"],
  "parameters": [{
    "name": "my_file",
    "allowed": ["thing1", "thing2"]
  }],
  "log": false,
  "ephemeral": false,
  "response": "code",
  "permissions": ["all"]
}
```
And be triggered by typing `bashbot open thing1` or `bashbot open thing2` and it also implies that the files `thing1` and `thing2` already exist on the host running bashbot.

If instead you want a more dynamic list (bashbot CANNOT do free form text), your configuration might look like this:
```json
{
  "name": "Open file",
  "description": "Open file",
  "help": "bashbot open [my_file]",
  "trigger": "open",
  "location": "./",
  "command": ["open ${my_file}"],
  "parameters": [{
    "name": "my_file",
    "allowed": [],
    "description": "All .md files in this directory",
    "source": [
      "ls *.md"
    ]
  }],
  "log": false,
  "ephemeral": false,
  "response": "code",
  "permissions": ["all"]
}
```
And then be triggered like this `bashbot open README.md`

because the output of the parameter source
```bash
$ ls *.md
README.md
```

The [describe example](https://github.com/mathew-fleisch/bashbot/tree/main/examples/describe) uses jq to build a list of valid parameters.

```json
{
  "name": "Describe Bashbot [command]",
  "description": "Show the json object for a specific command",
  "help": "bashbot describe [command]",
  "trigger": "describe",
  "location": "./",
  "command": ["jq '.tools[] | select(.trigger==\"${command}\")' ${BASHBOT_CONFIG_FILEPATH}"],
  "parameters": [
    {
      "name": "command",
      "allowed": [],
      "description": "a command to describe ('bashbot list')",
      "source": ["jq -r '.tools[] | .trigger' ${BASHBOT_CONFIG_FILEPATH}"]
    }
  ],
  "log": false,
  "ephemeral": false,
  "response": "code",
  "permissions": ["all"]
}
```

The valid parameters in this case list the possible triggers in the configuration file

```bash
$ jq -r '.tools[] | .trigger' ${BASHBOT_CONFIG_FILEPATH}
info
list
describe
test
time
version
ping
latest-release
trigger-github-action
asdf
list-examples
add-example
remove-example
```
I'll often pair these types of commands with a [list command](https://github.com/mathew-fleisch/bashbot/tree/main/examples/list) to show the possible options

**Comment by KacperKlys** [comment]
Hi @mathew-fleisch,
I had to build list of valid parameters using custom shell command. 
Thanks a lot for your help

**Comment by mathew-fleisch** [comment]
@KacperKlys please submit a PR if you can make the documentation more clear. Thanks for trying Bashbot!
